### PR TITLE
Update to flow-go v0.34.0-crescendo-preview.1

### PR DESCRIPTION
**Pull request by turbolent**
## Description

Automatically update to:
- [onflow/cadence v1.0.0-M7](https://github.com/onflow/cadence/releases/tag/v1.0.0-M7)
- [onflow/flow-go-sdk v1.0.0-M4](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-M4)
- [onflow/flow-go 6b0ce48](https://github.com/onflow/flow-go/commit/6b0ce48)
- [onflow/flow-emulator v1.0.0-M6](https://github.com/onflow/flow-emulator/releases/tag/v1.0.0-M6)
- [onflow/cadence-tools/test v1.0.0-M4](https://github.com/onflow/cadence-tools/test/releases/tag/v1.0.0-M4)
- [onflow/cadence-tools/lint v1.0.0-M4](https://github.com/onflow/cadence-tools/lint/releases/tag/v1.0.0-M4)
- [onflow/cadence-tools/languageserver v1.0.0-M3](https://github.com/onflow/cadence-tools/languageserver/releases/tag/v1.0.0-M3)
- [onflow/flixkit-go eaab0d6](https://github.com/onflow/flixkit-go/commit/eaab0d6)
- [onflow/flowkit/v2 v2.0.0-stable-cadence-alpha.4](https://github.com/onflow/flowkit/v2/releases/tag/v2.0.0-stable-cadence-alpha.4)

### CODE REVIEW

**Comment by turbolent** [comment]
Some tests are failing, don't know why. Likely some inconsistency betweem flowkit/flixkit-go/flow-cli master/this feature branch

**Review by janezpodhostnik — APPROVED** [review]

**Comment by bluesign** [comment]
> Some tests are failing, don't know why. Likely some inconsistency betweem flowkit/flixkit-go/flow-cli master/this feature branch

there was a recent PR to add context to some methods on flowkit. https://github.com/onflow/flowkit/pull/9

**Comment by bthaile** [comment]
I updated the PR to fix flixkit-go dependency and other methods that needed context.

**Review by bthaile — APPROVED** [review]
lgtm, I added flixkit-go dependency fixes as well.

**Comment by turbolent** [comment]
Thanks for fixing up the dependencies @bthaile 🙏

**Pull request merged**
