### PR TITLE
Update to Cadence v0.27.0 and Emulator v0.37.0

### PR DESCRIPTION
**Pull request by turbolent**
## Description

Update to
- [Cadence v0.27.0](https://github.com/onflow/cadence/releases/tag/v0.27.0)
- [Go SDK v0.28.0](https://github.com/onflow/flow-go-sdk/releases/tag/v0.28.0)
- [Emulator v0.37.0](https://github.com/onflow/flow-emulator/releases/tag/v0.37.0)

In addition, the language server and linter moved to https://github.com/onflow/cadence-tools.

______

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Comment by sideninja** [comment]
Looks good. Missing tidy so test run.

**Comment by turbolent** [comment]
CI reports the go.mod file needs updates, but locally `go mod tidy` produces no changes. Maybe that's because CI is on 1.18 and I have 1.19 locally? Maybe we can bump to 1.19 on CI?

**Comment by turbolent** [comment]
I see, thank you for the context! We can definitely leave it as-is or change it to the way you think it should be – I don't know either how flowkit came to be a module, though it seems to make sense (once it's ready to be used standalone of course).

What is the workflow for updating dependencies at the moment? Should I leave this PR open, and update downstream dependencies to the latest commit of this PR, then come back here and update the root go.mod to use the updated dependencies?

**Review by SupunS — APPROVED** [review]

**Comment by sideninja** [comment]
> I see, thank you for the context! We can definitely leave it as-is or change it to the way you think it should be – I don't know either how flowkit came to be a module, though it seems to make sense (once it's ready to be used standalone of course).
> 
> What is the workflow for updating dependencies at the moment? Should I leave this PR open, and update downstream dependencies to the latest commit of this PR, then come back here and update the root go.mod to use the updated dependencies?

I can help here and make a release. But the problematic flow is only with LS and yes, I usually draft up PR in CLI update things in LS and reference commit from draft PR in CLI and then merge that in and update the CLI to reference concrete version tag possibly. I've written about it here as well https://www.notion.so/dapperlabs/Releasing-and-maintaining-Go-DevX-Tools-da8beb1afd324b4aa72284f5ea1cb097#0de8293a1b7b4eba9aa560561ca13c51

**Review by sideninja — APPROVED** [review]

**Comment by turbolent** [comment]
@sideninja Thank you for writing this up! 👍

**Pull request merged**
