### PR TITLE
Update to Cadence v1.0.0-preview.30

### PR DESCRIPTION
**Pull request by turbolent**
## Description

Automatically update to:
- [onflow/cadence v1.0.0-preview.30](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.30)
- [onflow/flow-go-sdk v1.0.0-preview.31](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.31)
- [onflow/flow-go b968034713f6](https://github.com/onflow/flow-go/commit/b968034713f6)
- [onflow/flow-emulator v1.0.0-preview.25](https://github.com/onflow/flow-emulator/releases/tag/v1.0.0-preview.25)
- [onflow/cadence-tools/test v1.0.0-preview.30](https://github.com/onflow/cadence-tools/test/releases/tag/v1.0.0-preview.30)
- [onflow/cadence-tools/lint v1.0.0-preview.30](https://github.com/onflow/cadence-tools/lint/releases/tag/v1.0.0-preview.30)
- [onflow/cadence-tools/languageserver v1.0.0-preview.30](https://github.com/onflow/cadence-tools/languageserver/releases/tag/v1.0.0-preview.30)
- [onflow/flixkit-go v1.2.1-cadence-v1-preview.16](https://github.com/onflow/flixkit-go/releases/tag/v1.2.1-cadence-v1-preview.16)
- [onflow/flowkit/v2 v2.0.0-stable-cadence-alpha.21](https://github.com/onflow/flowkit/v2/releases/tag/v2.0.0-stable-cadence-alpha.21)
- [onflow/flow-evm-gateway v0.14.0](https://github.com/onflow/flow-evm-gateway/releases/tag/v0.14.0)

### CODE REVIEW

**Comment by turbolent** [comment]
@sideninja @m-Peter Can you please update `internal/evm/gateway.go` according to the changes in EVM Gateway?

**Comment by ianthpun** [comment]
@turbolent are you able to update the emulator to .26 here please? I would like those changes in here as well. Thanks!

**Comment by m-Peter** [comment]
@ianthpun I updated the emulator to .26 in https://github.com/onflow/flow-cli/pull/1631/commits/c4234b4b3e1c8c85b62f612f7b23f5edfb26fd9d.

@turbolent The CI is :white_check_mark:

**Comment by turbolent** [comment]
@m-Peter thank you!

@ianthpun Have the other dependencies which depend on the Emulator, like the language server also been updated?

**Comment by turbolent** [comment]
Given that not all dependencies have been updated yet to Emulator .26 I reverted the bump here, to unblock the urgently needed release of a preview CLI build.

**Comment by ianthpun** [comment]
@turbolent everything else has been merged in, the CLI is the last bit!

**Review by ianthpun — APPROVED** [review]

**Pull request merged**
