### PR TITLE
Added errors to accessors methods in config

### LINKED ISSUE #349: Getter methods ByName() for contracts, accounts, networks does not return error in config package
### Instructions

pkg/flowkit/config there are getters for getting configured contracts, networks, accounts. These return an empty pointer if they are not found. It is tempting to then chain together method calls. However if you have then misconfigured things you will get not so nice error messages. 

Should we fix this so that these return error as seond argument?

### PR DESCRIPTION
**Pull request by bjartek**
Closes #349 

## Description

______

For contributor use:

- [ ] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

**Comment by bjartek** [comment]
../../go/pkg/mod/github.com/onflow/cadence/languageserver@v0.18.2/integration/initialization.go:47:33: multiple-value state.Networks().ByName() in single-value context

I think we might need to change something in languageserver as well?

**Comment by sideninja** [comment]
> ../../go/pkg/mod/github.com/onflow/cadence/languageserver@v0.18.2/integration/initialization.go:47:33: multiple-value state.Networks().ByName() in single-value context
> 
> I think we might need to change something in languageserver as well?

Yep, this line should be updated: https://github.com/onflow/cadence/blob/master/languageserver/integration/initialization.go#L47

But probably also others, so the way you can test that is to pull language server locally, link version of the CLI/flowkit to the latest commit from this PR and then update all the changes, after that push the changes as part of PR and then link the latest commit in LS PR from the CLI so it passes tests.

**Review by sideninja — APPROVED** [review]
Looking great, thank you for improving the codebase 👌

**Comment by bjartek** [comment]
I already made a PR in LS, it is referecend above. https://github.com/onflow/cadence/pull/1102

**Pull request merged**
