### PR TITLE
Events last x blocks

### LINKED ISSUE #314: Ability to fetch events from the last x blocks
## Instructions

It is very useful to be able to fetch a certain event from the last number of x blocks.

Syntax could be
`flow events get <event> -10`.

That should resolve to latestBlock-10 latestBlock.

### Issue To Be Solved

Make it possible to fetch events for the last x blocks.

### PR DESCRIPTION
**Pull request by bjartek**
Closes #314 

## Description

______

For contributor use:

- [ ] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

**Review by sideninja — CHANGES_REQUESTED** [review]
This is a good functionality but it is lacking documentation update, linting error needs to be fixed, and also when running this command I get the following error: 
```
events get flow.AccountCreated -10 --network testnet
Error: unknown shorthand flag: '1' in -10
```
This has to do with cobra parsing `-` as a flag instead of a negative number.

**Comment by bjartek** [comment]
events get --network ... -- name -10 should work?

**Comment by bjartek** [comment]
```
flow events get -n mainnet -- A.1654653399040a61.FlowToken.TokensDeposited -10
```
This works for me, but I think flags are better here.

**Comment by bjartek** [comment]
This PR is not needed anymore if #319 is accepted since it uses flags to do the same in a more elegant way

**Pull request closed without merging**
