### PR TITLE
added command to add contract to the flow.json

### PR DESCRIPTION
**Pull request by bjartek**
#88 

## Description

Command to add an contract to the project struct

______

For contributor use:

- [ ] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

**Comment by bjartek** [comment]
I see here that i used args and not flags, that change is the last commit so we might want to revert that. IMHO this reads better with args, since it is just key=value, but if you want to add an alias to testnet, mainnet I can see the argument for flags.

**Comment by sideninja** [comment]
@bjartek great work :) 

I think this args/flags dilemma will be solved when we finish the CLI guideline as at that time we will go through all commands and make them consistent. I think args is fine for now.

**Comment by bjartek** [comment]
I tried to rebase this off newest master, but not sure if it even makes sense anymore. Should we just delete this and start anew?

**Comment by sideninja** [comment]
I was thinking this to become part of #124 (init section in the comment) where we create a `config` top command that has subcommands for adding/removing/viewing config values.

**Pull request closed without merging**
