### PR TITLE
event encoding fix for legacy typeid

### LINKED ISSUE #659: Flow-Cli 0.39.3 unable to retrieve transaction
### Problem

Flow-cli crashes when retrieving transactions in json format via cmd-line or runs endless

### Steps to Reproduce

Examples:
flow transactions get 312741367b158b1c63e39c22cb34026b88334723678d76b7253f06b790b0f911 -n mainnet -o json - crash
flow transactions get 16de57b007aa44dee2280231e7490a420f0f1c34b2212f438b74c156636553c8 -n mainnet -o json - endless no return

### Context

Blocks from providing tax relevant information.

### PR DESCRIPTION
**Pull request by bluesign**
On the way to close #659

## Description

@SupunS  informed about event.Payload, which solves our problems totally. 
______

For contributor use:

- [X] Targeted PR against `master` branch
- [X] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [X] Code follows the [standards mentioned here](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation
- [X] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

**Review by SupunS — APPROVED** [review]
Thank you for sending the fix! LGTM!

Would it be possible to add a test-case to verify the behaviour?

**Comment by bluesign** [comment]
yeah I need to get help from @sideninja on this I guess @SupunS , I really don't have any good idea to test this.

**Comment by sideninja** [comment]
> yeah I need to get help from @sideninja on this I guess @SupunS , I really don't have any good idea to test this.

You could have a test by creating an event and passing it to the TransactionResult struct and then asserting the method response.

**Review by sideninja — APPROVED** [review]
Works great, thanks!

**Comment by bluesign** [comment]
> @bluesign rearrange imports to satisfy CI

I will handle it and tests max tomorrow, had.a busy few days lately.

**Comment by sideninja** [comment]
@bluesign I will fix the linting as this is an important improvement I will merge for today release and resolve it myself. Thank you

**Pull request merged**
