### PR TITLE
add support for getting transactions and results from emulator by block id

### PR DESCRIPTION
**Pull request by bjartek**
Implement methods to get transactions and results by block id.

### CODE REVIEW

**Comment by chasefleming** [comment]
@bjartek awesome thanks for grabbing this! Can you expand in PR title so it's clear when it gets pulled into the release notes please?

**Comment by bjartek** [comment]
> @bjartek awesome thanks for grabbing this! Can you expand in PR title so it's clear when it gets pulled into the release notes please?

Better now?

**Comment by chasefleming** [comment]
Yes thanks @bjartek !

**Review by chasefleming — APPROVED** [review]

**Comment by chasefleming** [comment]
@bjartek this doesn't require a dependency update does it?

**Comment by bjartek** [comment]
Does not look like it. This was probably just forgotten when the dep was upgraded

**Pull request merged**
