### PR TITLE
added envsubst

### LINKED ISSUE #84: Configuration for private accounts in environment variables
### Issue To Be Solved

@psiemens wrote:
I think the highest priority is to give users a way to securely specify a few pieces of private data, and that can be solved easily and quickly with environment variable support. Do you think we could implement support for environment variables in this sprint, and then do flow.private.json as a follow-up feature?

I was looking at other examples and it looks like this syntax is quite common:

```
...
	"accounts": {
		"testnet-account": {
			"address": "f8d6e0586b0a20c7",
			"keys": "${env:MY_PRIVATE_KEY}"
		}
	},
...
```

A few examples:

https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables
https://www.serverless.com/framework/docs/providers/aws/guide/variables#referencing-environment-variables
https://www.elastic.co/guide/en/beats/winlogbeat/current/using-environ-vars.html

### PR DESCRIPTION
**Pull request by bjartek**
Closes #84 

Added envsubst and applied it to loading the proejct file

______

For contributor use:

- [x] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

**Comment by bjartek** [comment]
Should probably also update some documentation somewhere but I do not have the overview to see where that is.

**Comment by bjartek** [comment]
I get some test failure here that I do not understand, they are realted to code that I have not touched at all.

**Comment by psiemens** [comment]
Thanks for adding this! However, I think it'd a dupe of #87.

Also @sideninja and I thought we could use the `${env:VAR_NAME}` syntax. What do you think of that?

**Comment by bjartek** [comment]
Ok, I was s little confused.

https://github.com/drone/envsubst is another library that could have been used, I did not review them either that should probably have been done.

From my understanding neither of those librarires support your suggested syntax. If you feel that the cost og implementing your specifix syntax is worth it then do that. However the libraries have many features and emulates envsubst from bash that is a pattern that are well known.

In cases like theese I fins that I like to spend my innvoation points elsewhere and use a standard sollution. The choice however is not mine, it is yours :)

Really happy that we can focus on these issues do that it will be easier to get new devs up to speed with good tools.

**Comment by sideninja** [comment]
@bjartek  I like your implementation and I agree we should leverage the work of others by using a library. I want it to be our choice ;) 

The only comment I would have on this implementation is that I think it's a good design decision to put that functionality in this file: https://github.com/onflow/flow-cli/blob/private-config-file/flow/project/cli/config/processor.go 

I would keep that design of having a "preprocessor" of config files so the JSON config is not affected by this change, in my current refactoring I also removed loading of files from JSON as I don't think that is the correct place for loading files and hence your change won't work there. Let me know what you think.

**Comment by bjartek** [comment]
That makes total sense to me.

**Comment by bjartek** [comment]
That file has not been merge yet, can we just merge this and fix it later?

**Comment by psiemens** [comment]
> That file has not been merge yet, can we just merge this and fix it later?

@bjartek I'm good with that. I'll approve and merge 👍

**Review by psiemens — APPROVED** [review]
Nice and simple 👌

**Pull request merged**
