### PR TITLE
implement calling the new method to get tx by blockId

### PR DESCRIPTION
**Pull request by bjartek**
implement calling the method to get transactions and results by blockId for grpc, the underlying methods are not implemented for Backend so I have not implemented it for Emulator.

### CODE REVIEW

**Comment by sideninja** [comment]
Thank you @bjartek 
Can you just make sure the test pass.

**Comment by bjartek** [comment]
I get confused when I edit flowkit code from the root of the folder because it picks up the go.mod from the parent file in nvim and not the go.mod in flowkit. 

Any eta on making flowkit its own repo?

**Comment by bjartek** [comment]
Maybe this is dependent on https://github.com/onflow/flow-cli/pull/755/files#diff-1b4735b99c48e793c3cd85ea0530d4794d2d1cb651b1248ab52c9e963d8d1e8e?

**Comment by sideninja** [comment]
> Maybe this is dependent on https://github.com/onflow/flow-cli/pull/755/files#diff-1b4735b99c48e793c3cd85ea0530d4794d2d1cb651b1248ab52c9e963d8d1e8e?

Better to avoid updating Cadence if not needed. 

Yes, will work on flowkit improvements soon. I'm not sure if separating might happen soon tho, because working on CLI will become very hard since you will have to first make flowkit updates and then change CLI based on that, but often both are done at the same time. Even if extracted I will look into submodules for that.

**Review by sideninja — APPROVED** [review]

**Comment by sideninja** [comment]
Dependent on: #755

**Review by janezpodhostnik — APPROVED** [review]

**Pull request merged**
