### PR TITLE
Flag "--skip-check" added

### LINKED ISSUE #672: Feature: Allow to skip version check via flag
### Issue To Be Solved
Running any command via CLI will result in version check, which on slow connection can add overhead of multiple seconds(!).
In my case it was `320 ms` (offline) vs `12,000 ms`(slow connection) to spin up emulator. 

### Solution
Add `--skip-check` global flag to bypass version check and speed up execution of commands.

### (Optional): Context
Running tests via `flow-js-testing` was taking too much time to start emulator.
Disabling internet connection speed up start up process by `~3,750%` 😅

### PR DESCRIPTION
**Pull request by MaxStalker**
Closes #672 

## Description

- `internal/command/flags.go` - added new flag `SkipVersionCheck` to a list of flags
- `internal/command/command.go` - wrapped `checkVersion` call in a condition, based on aforementioned flag

______

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Review by sideninja — COMMENTED** [review]
Could we maybe just rename the flag to `--skip-version-check` as it's more obvious which check to skip.

**Comment by sideninja** [comment]
@MaxStalker can you look into this?

**Comment by MaxStalker** [comment]
@sideninja sure thing! :)
I was considering to propose to make this `true` by default, but then I thought it's probably more beneficial to have it disabled.

**Comment by sideninja** [comment]
> @sideninja sure thing! :) I was considering to propose to make this `true` by default, but then I thought it's probably more beneficial to have it disabled.

Yeah this should not be skipped by default.

**Comment by sideninja** [comment]
@MaxStalker looks good now, just make sure the flag is also added to the docs.

**Comment by sideninja** [comment]
> @sideninja are they in [Flow CLI Repo - Docs](https://github.com/onflow/flow-cli/tree/master/docs) or [Flow Repo - Docs](https://github.com/onflow/flow/docs)? 🤔

You can find them here https://github.com/onflow/flow-cli/tree/master/docs
And you should add that to the template: https://github.com/onflow/flow-cli/blob/master/docs/template.md 
And also to all the commands to the bottom where all global flags are.

**Comment by sideninja** [comment]
@MaxStalker I'm seeing some mixed changes in your PR. Could you make sure that it's up to date with master.

**Comment by MaxStalker** [comment]
> @MaxStalker I'm seeing some mixed changes in your PR. Could you make sure that it's up to date with master.

This is weird, I simply rebased my branch on latest master...

**Comment by MaxStalker** [comment]
- Fixed list of changed files
- Updaged documentation

**Review by sideninja — APPROVED** [review]
Nice, thank you 👍

**Pull request merged**
