### PR TITLE
Use flow cli repo version.txt in install.sh

### LINKED ISSUE #602: `version.txt` occasionally out of sync with latest version
### Problem

The `version.txt` on the master branch sometimes fails to upload to the GCS bucket where pre-built binaries are published. This prevents the Linux/macOS install script from being able to install the latest version of the CLI.

Does it make any sense to just link to the `version.txt` that's on the master branch, or could that be out of sync with the binaries in GCS?

cc @sideninja @sukantoraymond

### PR DESCRIPTION
**Pull request by sukantoraymond**
Closes #602 

This PR changes version checking from google cloud version.txt to flow cli repo version.txt in install.sh and install.ps1
______

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Comment by gpavlov2016** [comment]
I'm concerned about a situation where someone pushes an update to master with version update but does not release a new package right away to google - we will have a mismatch again.
More robust solution would be implementing verification and retries in case the version.txt upload failed during release.

**Comment by sukantoraymond** [comment]
With this PR, no more checking google for version number. It will all come from version.txt in flow cli repo

**Comment by sideninja** [comment]
Have you tested this out manually?

**Comment by sukantoraymond** [comment]
Tested 
````
Raymonds-MBP-3:flow-cli raymondsukanto$ sh install.sh
Downloading version v0.39.1 ...
````

**Review by sideninja — APPROVED** [review]

**Pull request merged**
