### PR TITLE
add prefix to user address when processing flow.json

### PR DESCRIPTION
**Pull request by bthaile**
Closes: https://github.com/onflow/flow-cli/issues/1330

## Description

add prefix to user address when processing flow.json
______

For contributor use:

- [x] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

**Review by bjartek — APPROVED** [review]

**Review by chasefleming — CHANGES_REQUESTED** [review]
There should be a Go SDK utility to do this. I think it's `HexToAddress`

**Review by bjartek — CHANGES_REQUESTED** [review]
I think address has a Hex method that will do this.

**Review by chasefleming — APPROVED** [review]
Just a heads up, this file is getting close to needing some tests

**Comment by chasefleming** [comment]
@bthaile looks like lint step didn't pass

**Comment by bthaile** [comment]
> Just a heads up, this file is getting close to needing some tests

https://github.com/onflow/flow-cli/issues/1335
created this ticket to track adding unit tests. I've moved a lot of the complexity to flixkit-go itself, I do agree flix.go needs tests.

**Comment by bthaile** [comment]
> I think address has a Hex method that will do this.

`Hex()` does not include "0x" that I see, maybe it's how I'm printing out the string fmt.Println or fmt.Sprintf doesn't print out a leading "0x"

**Comment by bthaile** [comment]
> `Hex()` does not include "0x" that I see, maybe it's how I'm printing out the string fmt.Println or fmt.Sprintf doesn't print out a leading "0x"

Hex() does not include "0x" that I see, maybe it's how I'm printing out the string fmt.Println or fmt.Sprintf doesn't print out a leading "0x". I changed to use BytesToAddress to create a flow.Address `address := flow.BytesToAddress([]byte(addr))`

**Comment by chasefleming** [comment]
@bthaile Can you create an issue in Go SDK if there is no method available for what you need so it's available in the future for others? You can also also make the PR to the Go SDK so we are avoiding hardcoding.

**Comment by bthaile** [comment]
> @bthaile Can you create an issue in Go SDK if there is no method available for what you need so it's available in the future for others? You can also also make the PR to the Go SDK so we are avoiding hardcoding.

flow-go-sdk, added issue and PR.
https://github.com/onflow/flow-go-sdk/pull/554

Any other blockers on this PR?

**Comment by bthaile** [comment]
> I think address has a Hex method that will do this.

nope `Hex()` does not add "0x"

**Review by bjartek — APPROVED** [review]

**Pull request merged**
