### PR TITLE
Update feature branch with master

### PR DESCRIPTION
**Pull request by ianthpun**
______

For contributor use:

- [ ] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

**Comment by turbolent** [comment]
Thank you for keeping this updated!

I had a look at the conflict resolution (`git log -1 -p -w --remerge-diff c053a6ac30c3de6d2265365d997085737f10e89e`) and it looks good. Unfortunately, due to https://github.com/onflow/flow-core-contracts/issues/433, these two changes need to get reverted (i.e. counter-intuitively, the _lower_ versions are the actual current versions):

```diff
-       github.com/onflow/flow-core-contracts/lib/go/templates v1.0.0
+       github.com/onflow/flow-core-contracts/lib/go/templates v1.2.4-0.20231016154253-a00dbf7c061f

-       github.com/onflow/flow-core-contracts/lib/go/contracts v1.1.0 // indirect
+       github.com/onflow/flow-core-contracts/lib/go/contracts v1.2.4-0.20231016154253-a00dbf7c061f // indirect
```

The fixes, faebf02b45d5f4eea513931a080e3e3c8489b569 and 970ab037180534e99babc917f8a47ed1c4da56b6, look good, too!

**Review by turbolent — APPROVED** [review]
👍

**Comment by chasefleming** [comment]
@turbolent The versions I added were what are on the stable cadence branch currently? If I revert those changes, it breaks.

**Comment by turbolent** [comment]
@chasefleming Yep, all I meant to do above was confirm that your fixes are correct 👍

**Review by chasefleming — APPROVED** [review]

**Pull request merged**
