### PR TITLE
Remove invalid mdx expression.

### PR DESCRIPTION
**Pull request by 10thfloor**

### CODE REVIEW

**Comment by sideninja** [comment]
@10thfloor can you update with master there are some problems.

**Comment by sideninja** [comment]
This is getting stale. @10thfloor let me know if you want to get it in or else should I close it.

**Comment by 10thfloor** [comment]
Ok I'll update this.

**Comment by sideninja** [comment]
@10thfloor kind reminder, will put into draft meanwhile so I don't keep getting notified

**Pull request closed without merging**
