### PR TITLE
Update to Cadence v1.0.0-preview.49

### PR DESCRIPTION
**Pull request by turbolent**
## Description

Automatically update to:
- [onflow/cadence v1.0.0-preview.49](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.49)
- [onflow/flow-go-sdk v1.0.0-preview.51](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.51)
- [onflow/flow-go 8b4fff2114d4](https://github.com/onflow/flow-go/commit/8b4fff2114d4)
- [onflow/flow-emulator v1.0.0-preview.40](https://github.com/onflow/flow-emulator/releases/tag/v1.0.0-preview.40)
- [onflow/cadence-tools/test v1.0.0-preview.37](https://github.com/onflow/cadence-tools/test/releases/tag/v1.0.0-preview.37)
- [onflow/cadence-tools/lint v1.0.0-preview.37](https://github.com/onflow/cadence-tools/lint/releases/tag/v1.0.0-preview.37)
- [onflow/cadence-tools/languageserver v1.0.0-preview.37](https://github.com/onflow/cadence-tools/languageserver/releases/tag/v1.0.0-preview.37)
- [onflow/flixkit-go v1.2.1-cadence-v1-preview.23](https://github.com/onflow/flixkit-go/releases/tag/v1.2.1-cadence-v1-preview.23)
- [onflow/flowkit/v2 v2.0.0-stable-cadence-alpha.31](https://github.com/onflow/flowkit/v2/releases/tag/v2.0.0-stable-cadence-alpha.31)
- [onflow/flow-evm-gateway v0.29.4](https://github.com/onflow/flow-evm-gateway/releases/tag/v0.29.4)

### CODE REVIEW

**Review by nvdtf — APPROVED** [review]

**Comment by turbolent** [comment]
@SupunS It looks like we need to export the type requirement extraction from the migration code in flow-go and run it here?

**Comment by SupunS** [comment]
> @SupunS It looks like we need to export the type requirement extraction from the migration code in flow-go and run it here?

ah yeah, would have to extract those from the emulator state

**Comment by turbolent** [comment]
@SupunS do we have to extract from all contracts (which ones? (transitive) imports?) or is the validated contract enough?

**Comment by SupunS** [comment]
Have to detect from all dependencies (but only for dependencies in the staged contracts list. e.g: no need for system contracts). Was looking at the code, I think we can first visit all staged contracts to extract the type-requirements, and then run the validation

**Comment by SupunS** [comment]
@turbolent Opened https://github.com/onflow/flow-cli/pull/1705

**Pull request merged**
